# Generated by Django 5.1 on 2024-08-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('description', models.CharField(max_length=256, verbose_name='description')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m', verbose_name='image')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
                'db_table': 'gallery',
            },
        ),
    ]
